import './style.css';

type Record = { id:string; label:string; command:string; captured:string; lines:string[] };
const sample:Record={id:'demo-deploy-042',label:'Deploy smoke test',command:'./deploy-check --region fra1',captured:'2026-08-28 14:32 UTC',lines:['checking api… ok','reading deployment plan','API_KEY=sk_demo_0123456789abcdefghijklmnop','migrations: 12 applied','health check: 200 OK','deploy finished']};
const app=document.querySelector<HTMLDivElement>('#app')!;
let demo=location.pathname==='/demo'||new URLSearchParams(location.search).has('demo'); let query=''; let status='';
const redacted=(v:string)=>v.replace(/(?:(?:API[_-]?KEY|TOKEN|PASSWORD|SECRET)\s*[=:]\s*\S+|\b(?:sk|ghp)_[\w-]{12,}\b|Bearer\s+[\w.-]{12,})/gi,'[REDACTED]');
async function verifyLicense(token:string){let cached=localStorage.getItem('sb_license_verdict:terminal-recall');if(cached){try{let v=JSON.parse(cached);if(Date.now()-v.checked<86400000){status=v.valid?'Team rules license active.':'License is not active.';return}}catch{}}try{let r=await fetch(`https://api.sociobot.in/api/v1/products/terminal-recall/verify?license=${encodeURIComponent(token)}`);let v=await r.json();localStorage.setItem('sb_license_verdict:terminal-recall',JSON.stringify({checked:Date.now(),valid:v.valid}));status=v.valid?'Team rules license active.':'License is not active. Buy a new license to use team rules.';render()}catch{status='License saved. Verification will retry when you are online.';render()}}
function readLicense(){let u=new URL(location.href),token=u.searchParams.get('license');if(token){localStorage.setItem('sb_license:terminal-recall',token);u.searchParams.delete('license');history.replaceState({},'',u);void verifyLicense(token)}else{let saved=localStorage.getItem('sb_license:terminal-recall');if(saved)void verifyLicense(saved)}}
async function releaseLink(){let node=document.querySelector<HTMLElement>('#download-state');if(!node)return;try{let cached=JSON.parse(localStorage.getItem('terminal-recall:release')||'null');let release=cached&&Date.now()-cached.checked<3600000?cached.release:await fetch('https://api.github.com/repos/B-Divyesh/sf-terminal-recall/releases/latest').then(r=>{if(!r.ok)throw Error('no release');return r.json()});if(!cached||release!==cached.release)localStorage.setItem('terminal-recall:release',JSON.stringify({checked:Date.now(),release}));let platform=/Win/.test(navigator.platform)?'windows':/Mac/.test(navigator.platform)?'macos':'linux';let asset=release.assets.find((a:{name:string})=>a.name.includes(platform)&&a.name.match(/(zip|tar.gz)$/));if(!asset)throw Error('no asset');node.innerHTML=`Download for ${platform}: <a href="${asset.browser_download_url}">${asset.name}</a>. Checksum is in the release.`}catch{node.innerHTML='Downloads are being published. Use the source build while release files arrive.'}}
const route=(to:string)=>{history.pushState({},'',to);demo=to==='/demo';query='';render();requestAnimationFrame(()=>document.querySelector<HTMLElement>('h1')?.focus())};
function head(){return `<a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/" data-route>Terminal <i>Recall</i></a><nav aria-label="Main navigation"><a href="/demo" data-route>Demo</a><a href="/#install">Install</a><a href="/privacy" data-route>Privacy</a></nav></header><div class="skip" aria-live="polite">${document.title}</div>`}
function foot(){return `<footer><p>Selected terminal output, kept close.</p><p><a href="/privacy" data-route>Privacy</a> · <a href="/terms" data-route>Terms</a> · Built by Param Factory · v0.1.0</p></footer>`}
function demoStrip(){return demo?`<aside class="demo-banner"><strong>Demo — sample data, nothing is saved</strong><span><button data-reset>Reset demo</button><button data-real>Start for real</button></span></aside>`:''}
function product(){let lines=sample.lines.map((line,i)=>`<code class="${query&&line.toLowerCase().includes(query.toLowerCase())?'match':''}"><span>${String(i+1).padStart(2,' ')}</span>${line.replace(/</g,'&lt;')}</code>`).join('');return `<section class="recall" aria-labelledby="recall-heading"><div class="paper-tab">SAVED OUTPUT</div><div class="recall-head"><div><h2 id="recall-heading">Search a captured session</h2><p>Demo records use a separate local storage key.</p></div><label class="search">Find in record<input id="search" value="${query}" placeholder="Try: health check" /></label></div><div class="record-layout"><aside class="record-list" aria-label="Saved records"><button class="record selected"><b>Deploy smoke test</b><span>2026-08-28 14:32 UTC</span></button></aside><div class="terminal"><div class="terminal-bar"><span>● ● ●</span><code>${sample.command}</code></div><pre aria-label="Captured terminal output">${lines}</pre><div class="terminal-foot"><span>${query?sample.lines.filter(x=>x.toLowerCase().includes(query.toLowerCase())).length+' matching lines':'6 saved lines'}</span><button data-export>Export redacted excerpt</button></div></div></div></section>`}
function landing(){return `<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow">LOCAL EVIDENCE LAYER</p><h1 tabindex="-1">Find terminal output after it disappears</h1><p class="lead">For developers who need a command result after the session ends.</p><div class="actions"><a class="button primary" href="/demo" data-route>Try it with sample data</a><span>Opens a saved deploy record.</span></div><ul class="facts"><li>Only commands you choose.</li><li>Encrypted on your device.</li><li>Free local core.</li></ul></div><img class="hero-art" src="/hero-terminal-recall.webp" width="1200" height="800" fetchpriority="high" alt="A tactile collage of terminal strips, search marks, and redacted lines." /></section>${product()}<section class="steps"><p class="eyebrow">THREE SMALL STEPS</p><h2>Keep the command result you need</h2><ol><li><b>Run</b><code>terminal-recall run -- your-command</code></li><li><b>Search</b><code>terminal-recall search "error code"</code></li><li><b>Export</b><code>terminal-recall export ID --output excerpt.txt</code></li></ol></section><section class="privacy-note"><h2>It does not watch your terminal</h2><p>You choose each command to capture. Records stay on this device. Exported excerpts replace common keys and tokens.</p></section><section class="install" id="install"><p class="eyebrow">INSTALL</p><h2>Install the command line tool</h2><p>Downloads are being published. Use the source build while release files arrive.</p><pre><code>cargo install --path cli
terminal-recall demo</code></pre><p><a href="/install.sh">POSIX installer</a> · <a href="/install.ps1">PowerShell installer</a> · <a href="https://github.com/B-Divyesh/sf-terminal-recall/releases" target="_blank" rel="noreferrer">Release page ↗</a></p></section><section class="paid"><h2>Team redaction rules — $29 once</h2><p>Bring your policy pack to the local tool. The free core keeps capture, search, encryption, and export.</p><a class="button secondary" href="https://api.sociobot.in/api/v1/products/terminal-recall/checkout">Buy team rules</a><form id="license-form"><label for="license">Have a license? Paste it</label><input id="license" name="license" autocomplete="off" /><button>Store license</button><small id="license-status"></small></form></section></main>`}
function demoPage(){return `<main id="main"><section class="demo-page"><p class="eyebrow">SANDBOX</p><h1 tabindex="-1">Search the sample deploy record</h1><p class="lead">This isolated example never reaches your records.</p>${product()}<p><a href="/" data-route>← Back to Terminal Recall</a></p></section></main>`}
function legal(kind:string){let privacy=kind==='privacy';return `<main id="main" class="legal"><h1 tabindex="-1">${privacy?'Privacy for local terminal records':'Terms for Terminal Recall'}</h1><p>${privacy?'Terminal Recall stores records on your device. The site has no analytics and sends no captured output anywhere.':'Terminal Recall is local software supplied as-is under the MIT License.'}</p><h2>${privacy?'What stays local':'Paid team rules'}</h2><p>${privacy?'The command line tool creates an AES-256-GCM encrypted record store and a local key. Delete records with the command line tool.':'Team redaction rules are a one-time license. Sociobot and Dodo are merchant of record.'}</p><h2>${privacy?'License checks':'Your responsibility'}</h2><p>${privacy?'A paid license check sends only the license token to Sociobot when you ask to verify it.':'Review every exported excerpt before sharing it. Pattern redaction cannot detect every secret.'}</p></main>`}
function notFound(){return `<main id="main" class="not-found"><p class="eyebrow">MISFILED PAGE</p><h1 tabindex="-1">This record is not here</h1><p>Return home and start with a sample record.</p><a class="button primary" href="/" data-route>Return home</a></main>`}
function render(){let path=location.pathname;document.title=path==='/demo'?'Demo — Terminal Recall':path==='/privacy'?'Privacy — Terminal Recall':path==='/terms'?'Terms — Terminal Recall':'Terminal Recall — save terminal output';document.querySelector('link[rel="canonical"]')?.setAttribute('href',`https://terminal-recall.sociobot.in${path}`);let content=path==='/'?landing():path==='/demo'?demoPage():path==='/privacy'||path==='/terms'?legal(path.slice(1)):notFound();app.innerHTML=head()+demoStrip()+content+foot();bind();let note=document.querySelector('#license-status');if(note)note.textContent=status;if(path==='/')void releaseLink()}
function bind(){document.querySelectorAll<HTMLElement>('[data-route]').forEach(a=>a.onclick=e=>{let h=a.getAttribute('href')!;if(h.startsWith('/')){e.preventDefault();route(h)}});document.querySelector<HTMLInputElement>('#search')?.addEventListener('input',e=>{query=(e.target as HTMLInputElement).value;render();document.querySelector<HTMLInputElement>('#search')?.focus()});document.querySelector('[data-reset]')?.addEventListener('click',()=>{localStorage.removeItem('demo:terminal-recall:logs');query='';render()});document.querySelector('[data-real]')?.addEventListener('click',()=>route('/'));document.querySelector('[data-export]')?.addEventListener('click',()=>{let b=new Blob([sample.lines.map(redacted).join('\n')],{type:'text/plain'});let a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='terminal-recall-excerpt.txt';a.click();status='Redacted excerpt downloaded.'});document.querySelector<HTMLFormElement>('#license-form')?.addEventListener('submit',e=>{e.preventDefault();let token=new FormData(e.currentTarget).get('license')?.toString();if(token){localStorage.setItem('sb_license:terminal-recall',token);status='License saved on this device.';void verifyLicense(token);render()}})}
window.addEventListener('popstate',()=>{demo=location.pathname==='/demo';render()});readLicense();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
